
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kazim
 */
public class staffsignupPage extends javax.swing.JFrame {

    /**
     * Creates new form signupPage
     */
    public staffsignupPage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pic = new javax.swing.JLabel();
        QuantumCineplex = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        createAccount = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cnicField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        showpasswordButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        alreadyaccountLabel = new javax.swing.JLabel();
        signinButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupPic.jpg"))); // NOI18N

        QuantumCineplex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QuantumCineplex.setForeground(new java.awt.Color(255, 255, 255));
        QuantumCineplex.setText("QUANTUM CINEPLEX");

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        createAccount.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        createAccount.setForeground(new java.awt.Color(255, 255, 255));
        createAccount.setText("CREATE ACCOUNT");

        detailsLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        detailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        detailsLabel.setText("Enter your Details");

        fnameField.setForeground(new java.awt.Color(204, 204, 204));
        fnameField.setText("First Name");
        fnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFieldFocusLost(evt);
            }
        });

        lnameField.setForeground(new java.awt.Color(204, 204, 204));
        lnameField.setText("Last Name");
        lnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFieldFocusLost(evt);
            }
        });

        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.setText("Email Address");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        cnicField.setForeground(new java.awt.Color(204, 204, 204));
        cnicField.setText("CNIC");
        cnicField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicFieldFocusLost(evt);
            }
        });
        cnicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicFieldActionPerformed(evt);
            }
        });

        passwordField.setText("Password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        showpasswordButton.setBackground(new java.awt.Color(0, 0, 0));
        showpasswordButton.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        showpasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        showpasswordButton.setText("SHOW");
        showpasswordButton.setBorder(null);
        showpasswordButton.setBorderPainted(false);
        showpasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showpasswordButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showpasswordButtonMouseExited(evt);
            }
        });
        showpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordButtonActionPerformed(evt);
            }
        });

        signupButton.setBackground(new java.awt.Color(204, 0, 0));
        signupButton.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("SIGN UP");
        signupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupButtonMouseExited(evt);
            }
        });
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        alreadyaccountLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        alreadyaccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        alreadyaccountLabel.setText("Have an account?");

        signinButton.setBackground(new java.awt.Color(0, 0, 0));
        signinButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        signinButton.setForeground(new java.awt.Color(255, 255, 255));
        signinButton.setText("Sign in");
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinButtonMouseExited(evt);
            }
        });
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("H");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(detailsLabel)
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(QuantumCineplex)
                                        .addGap(85, 85, 85))
                                    .addComponent(createAccount, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(22, 22, 22)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cnicField)
                                            .addComponent(emailField)
                                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(showpasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alreadyaccountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signinButton)
                                .addGap(168, 168, 168))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(QuantumCineplex, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailsLabel)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showpasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cnicField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyaccountLabel)
                    .addComponent(signinButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setForeground(Color.WHITE);
        closeButton.setBackground(Color.RED);
        closeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setForeground(Color.WHITE);
        closeButton.setBackground(Color.BLACK);
        closeButton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_closeButtonMouseExited

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void cnicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicFieldActionPerformed

    private void fnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFieldFocusGained
        if (fnameField.getText().equals("First Name")) {
            setPromptText(fnameField, null);
        }
    }//GEN-LAST:event_fnameFieldFocusGained

    private void fnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFieldFocusLost
        if (fnameField.getText().trim().isEmpty()) {
            setPromptText(fnameField, "First Name");
        }
    }//GEN-LAST:event_fnameFieldFocusLost

    private void lnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFieldFocusGained
        if (lnameField.getText().equals("Last Name")) {
            setPromptText(lnameField, null);
        }
    }//GEN-LAST:event_lnameFieldFocusGained

    private void lnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFieldFocusLost
        if (lnameField.getText().trim().isEmpty()) {
            setPromptText(lnameField, "Last Name");
        }
    }//GEN-LAST:event_lnameFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        if (emailField.getText().equals("Email Address")) {
            setPromptText(emailField, null);
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if (emailField.getText().trim().isEmpty()) {
            setPromptText(emailField, "Email Address");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void cnicFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFieldFocusGained
        if (cnicField.getText().equals("CNIC")) {
            setPromptText(cnicField, null);
        }
    }//GEN-LAST:event_cnicFieldFocusGained

    private void cnicFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFieldFocusLost
        if (cnicField.getText().trim().isEmpty()) {
            setPromptText(cnicField, "CNIC");
        }
    }//GEN-LAST:event_cnicFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (passwordField.getText().equals("Password")) {
            setPromptText(passwordField, null);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getText().trim().isEmpty()) {
            setPromptText(passwordField, "Password");
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void signupButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseEntered
        signupButton.setForeground(Color.BLACK);
        signupButton.setBackground(Color.WHITE);
        signupButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signupButtonMouseEntered

    private void signupButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseExited
        signupButton.setForeground(Color.WHITE);
        signupButton.setBackground(Color.RED);
        signupButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signupButtonMouseExited

    private void signinButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseEntered
        signinButton.setBackground(Color.RED);
        signinButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signinButtonMouseEntered

    private void signinButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseExited
        signinButton.setBackground(Color.BLACK);
        signinButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signinButtonMouseExited

    private void showpasswordButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordButtonMouseEntered
        showpasswordButton.setForeground(Color.BLACK);
        showpasswordButton.setBackground(Color.WHITE);
        showpasswordButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_showpasswordButtonMouseEntered

    private void showpasswordButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordButtonMouseExited
        showpasswordButton.setForeground(Color.WHITE);
        showpasswordButton.setBackground(Color.BLACK);
        showpasswordButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_showpasswordButtonMouseExited

    private void showpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordButtonActionPerformed
        if (passwordField.getEchoChar() == 0) {
            passwordField.setEchoChar('*');
            showpasswordButton.setText("SHOW");
        } else {
            passwordField.setEchoChar((char) 0);
            showpasswordButton.setText("HIDE");
        }
    }//GEN-LAST:event_showpasswordButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        if (lnameField.getText().trim().isEmpty() || fnameField.getText().trim().isEmpty() || cnicField.getText().trim().isEmpty() || emailField.getText().trim().isEmpty() || passwordField.getText().trim().isEmpty() || fnameField.getText().equals("First Name") || lnameField.getText().equals("Last Name") || emailField.getText().equals("Email Address") || passwordField.getText().equals("Password") || cnicField.getText().equals("Contact Number")) {
            JFrame f = null;
            JOptionPane.showMessageDialog(f, "Fields are Empty!", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean hasUppercase = false;
            boolean hasSpecialChar = false;

            for (char ch : passwordField.getText().toCharArray()) {
                if (Character.isUpperCase(ch)) {
                    hasUppercase = true;
                }
                if ("!@#$%^&*()".contains(String.valueOf(ch))) {
                    hasSpecialChar = true;
                }
            }
            if (passwordField.getText().length() == 8 && (hasUppercase || hasSpecialChar)) {
                dbconnection db = new dbconnection();
                String name = fnameField.getText() + " " + lnameField.getText();
                String sql = "insert into staff (NAME,EMAIL,PASSWORD,CNIC) values ('" + name + "','" + emailField.getText() + "','" + passwordField.getText() + "','" + cnicField.getText() + "')";
                try {
                    db.st.executeUpdate(sql);
                    JFrame f = null;
                    JOptionPane.showMessageDialog(f, "Success!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    staffLoginPage obj = new staffLoginPage();
                    obj.setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Try Again");
                    Logger.getLogger(signupPage.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JFrame f = null;
                JOptionPane.showMessageDialog(f, "Password must contain 8 digits and a Special Character or a UpperCase Letter!", "Error", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_signupButtonActionPerformed

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        dispose();
        staffLoginPage obj = new staffLoginPage();
        obj.setVisible(true);
    }//GEN-LAST:event_signinButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        backButton.setForeground(Color.WHITE);
        backButton.setBackground(Color.RED);
        backButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        backButton.setForeground(Color.WHITE);
        backButton.setBackground(Color.BLACK);
        backButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        Quantum_Cinéplex obj = new Quantum_Cinéplex();
        obj.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private static void setPromptText(JTextField textField, String prompt) {
        textField.setForeground(prompt == null ? Color.BLACK : Color.GRAY);
        textField.setText(prompt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffsignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel QuantumCineplex;
    private javax.swing.JLabel alreadyaccountLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField cnicField;
    private javax.swing.JLabel createAccount;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fnameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton showpasswordButton;
    private javax.swing.JButton signinButton;
    private javax.swing.JButton signupButton;
    // End of variables declaration//GEN-END:variables
}
